// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEdge(arg1, arg2, arg3, arg4) {
  return window['go']['presentation']['App']['AddEdge'](arg1, arg2, arg3, arg4);
}

export function CreateComponent(arg1, arg2) {
  return window['go']['presentation']['App']['CreateComponent'](arg1, arg2);
}

export function GetEditor() {
  return window['go']['presentation']['App']['GetEditor']();
}

export function ListCandidates() {
  return window['go']['presentation']['App']['ListCandidates']();
}

export function RemoveComponent(arg1) {
  return window['go']['presentation']['App']['RemoveComponent'](arg1);
}

export function RemoveEdge(arg1, arg2, arg3, arg4) {
  return window['go']['presentation']['App']['RemoveEdge'](arg1, arg2, arg3, arg4);
}

export function SetAssignment(arg1, arg2) {
  return window['go']['presentation']['App']['SetAssignment'](arg1, arg2);
}

export function UpdateEditor(arg1) {
  return window['go']['presentation']['App']['UpdateEditor'](arg1);
}
