// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presentation} from '../models';

export function AddEdge(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateComponent(arg1:string,arg2:presentation.Position):Promise<void>;

export function GetEditor():Promise<presentation.Editor>;

export function ListCandidates():Promise<presentation.Candidates>;

export function RemoveComponent(arg1:string):Promise<void>;

export function RemoveEdge(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetAssignment(arg1:string,arg2:presentation.Assignment):Promise<void>;

export function UpdateEditor(arg1:presentation.Editor):Promise<void>;
