// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function pipeline() {
    return invoke<Pipeline>("pipeline")
}

export function updatePipeline(updated: Pipeline) {
    return invoke<null>("update_pipeline", { updated })
}

export type OutputPort = { name: string }
export type Node = { type: string; id: string; data: NodeData; position: Position }
export type NodeData = { label: string; inputs: InputPort[]; outputs: OutputPort[] }
export type Edge = { id: string; label: string | null; source: string; target: string; sourceHandle: string; targetHandle: string }
export type Pipeline = { nodes: Node[]; edges: Edge[] }
export type InputPort = { name: string }
export type Position = { x: number; y: number }
