// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function candidates() {
    return invoke<Candidate[]>("candidates")
}

export function createComponent(kind: string, position: Position) {
    return invoke<null>("create_component", { kind,position })
}

export function editor() {
    return invoke<Editor>("editor")
}

export function updateEditor(updated: Editor) {
    return invoke<null>("update_editor", { updated })
}

export type OutputPort = { parent: string; name: string; properties: string[] }
export type Candidate = { kind: string; label: string }
export type Position = { x: number; y: number }
export type Edge = { id: string; label: string | null; source: string; target: string; sourceHandle: string; targetHandle: string; data: EdgeData }
export type InputPort = { parent: string; name: string; properties: string[] }
export type EdgeData = { assign: { [key: string]: string } }
export type Editor = { nodes: Node[]; edges: Edge[] }
export type NodeData = { label: string; inputs: InputPort[]; outputs: OutputPort[] }
export type Node = { id: string; type: string; position: Position; data: NodeData }
